//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hibicusWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_a7c3cb_hibicuswebEntities2 : DbContext
    {
        public db_a7c3cb_hibicuswebEntities2()
            : base("name=db_a7c3cb_hibicuswebEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Genero> Generoes { get; set; }
        public virtual DbSet<Resennia> Resennias { get; set; }
        public virtual DbSet<Reserva> Reservas { get; set; }
        public virtual DbSet<Rol_Usuario> Rol_Usuario { get; set; }
        public virtual DbSet<Servicio> Servicios { get; set; }
        public virtual DbSet<Tipo_Servicio> Tipo_Servicio { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
