//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hibicusWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int id_Reserva { get; set; }
        public System.DateTime fecha_Hora { get; set; }
        public int id_Cliente { get; set; }
        public int id_Empleado { get; set; }
        public int id_Servicio { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}
